#!/usr/bin/env python3.12
"""Retired-controller engine shells for family qwen (H1/J2). Bodies in _retired_shell."""
from __future__ import annotations
from pathlib import Path
from tools.condense.tests._retired_shell import launcher, lease, lifecycle, reseal
FAMILY = 'qwen'

def test_geometry_decoupled_head_dim(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_geometry_decoupled_head_dim')
def test_classify_all_organ_classes(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_classify_all_organ_classes')
def test_classify_rejects_garbage(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_classify_rejects_garbage')
def test_expected_shapes(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_expected_shapes')
def test_synthetic_inventory_and_cross_check(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_synthetic_inventory_and_cross_check')
def test_synthetic_name_verification(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_synthetic_name_verification')
def test_synthetic_name_verification_detects_missing(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_synthetic_name_verification_detects_missing')
def test_topk_routing_shape(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_topk_routing_shape')
def test_topk_rejects_bad_k(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_topk_rejects_bad_k')
def test_bounded_read_stub_untested_pending_source(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_bounded_read_stub_untested_pending_source')
def test_bounded_read_executes_on_synthetic_shard(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_bounded_read_executes_on_synthetic_shard')
def test_real_architecture(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_real_architecture')
def test_real_name_scheme(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_real_name_scheme')
def test_real_grand_total_235b_438gib(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_real_grand_total_235b_438gib')
def test_real_shard_plan_and_counts(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_real_shard_plan_and_counts')
def test_real_bounded_read_pending(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_real_bounded_read_pending')
def test_whole_model_plan_reaches_120b_rate_without_hiding_nonexperts(tmp_path: Path) -> None: launcher(tmp_path, FAMILY, 'test_whole_model_plan_reaches_120b_rate_without_hiding_nonexperts')
def test_expert_organ_allocation_is_below_target_but_not_mislabeled_whole_model(tmp_path: Path) -> None: launcher(tmp_path, FAMILY, 'test_expert_organ_allocation_is_below_target_but_not_mislabeled_whole_model')
def test_forge_pack_family_shape_and_bpw(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_forge_pack_family_shape_and_bpw')
def test_forge_pack_rejects_unknown_family(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_forge_pack_rejects_unknown_family')
def test_candidates_enumerate_over_three_qwen_classes(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_candidates_enumerate_over_three_qwen_classes')
def test_vulture_champion_maps_gateup_together_down_distinct(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_vulture_champion_maps_gateup_together_down_distinct')
def test_vulture_champion_fallback_when_priors_absent(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_vulture_champion_fallback_when_priors_absent')
def test_control_and_baseline_families(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_control_and_baseline_families')
def test_rows_are_decisive_first_and_unique(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_rows_are_decisive_first_and_unique')
def test_source_absent_seals_waiting_source(tmp_path: Path) -> None: reseal(tmp_path, FAMILY, 'test_source_absent_seals_waiting_source')
def test_lease_claim_refuse_and_checkpoint(tmp_path: Path) -> None: lease(tmp_path, FAMILY, 'test_lease_claim_refuse_and_checkpoint')
def test_other_heavy_lease_blocks_claim(tmp_path: Path) -> None: lease(tmp_path, FAMILY, 'test_other_heavy_lease_blocks_claim')
def test_reader_roundtrips_bf16_and_maps_shards(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_reader_roundtrips_bf16_and_maps_shards')
def test_bf16_rows_matches_full_gather(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_bf16_rows_matches_full_gather')
def test_remote_reader_uses_exact_ranges_and_cache(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_remote_reader_uses_exact_ranges_and_cache')
def test_remote_forward_matches_local_forward(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_remote_forward_matches_local_forward')
def test_forward_shapes_and_finiteness(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_forward_shapes_and_finiteness')
def test_qk_norm_detected_and_partial_blocks(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_qk_norm_detected_and_partial_blocks')
def test_nll_and_perplexity(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_nll_and_perplexity')
def test_forward_is_deterministic(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_forward_is_deterministic')
def test_expert_hook_is_called_and_changes_output(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_expert_hook_is_called_and_changes_output')
def test_standard_swiglu_differs_from_gptoss_clamped_gate(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_standard_swiglu_differs_from_gptoss_clamped_gate')
def test_router_softmax_first_topk_and_renorm(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_router_softmax_first_topk_and_renorm')
def test_rope_is_norm_preserving_and_identity_at_pos0(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_rope_is_norm_preserving_and_identity_at_pos0')
def test_real_meta_geometry_targets_qwen3_moe(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_real_meta_geometry_targets_qwen3_moe')
def test_real_source_is_untested_pending_source(tmp_path: Path) -> None: lifecycle(tmp_path, FAMILY, 'test_real_source_is_untested_pending_source')
